apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: yourusername/auth-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/authdb
        - name: PORT
          value: "3000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: food-delivery
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000