apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: kaveenash/order-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/orderdb
        - name: PORT
          value: "3002"